sudo: false
dist: trusty

language: node_js
node_js:
  - "7"
  - "6"

script:
 - echo "Running tests against $(node -v) ..."
 - npm test

jobs:
  include:
    - stage: npm release
      node_js: "7"
      cache:
        directories:
          - node_modules
      script:
        - echo "Deploying to npm ..."
        - npm publish
      deploy:
        provider: npm
        email: $NPM_EMAIL
        api_key: $NPM_API_KEY
        on:
          all_branches: true
          tags: true
          deploy-npm-release: true
