sudo: false
dist: trusty

language: node_js
node_js:
  - "7"
before_deploy:
  - npm install -g gulp
  - gulp --version

deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_API_KEY
  on:
    all_branches: true
    tags: true
    deploy-npm-release: true
